### PR TITLE
emoji-zooming local setting

### LINKED ISSUE #6: Make "zoom emoji on mouse-over" feature a user-controlled toggle
### Pitch

We added a feature to scale emoji on mouse-over. Make it a user preference in the glitch-soc pop-over

### Motivation

User choice is good, and necessary to propose a merge upstream

### PR DESCRIPTION
**Pull request by deanveloper**
fixes #6 

requires a refresh for the setting to apply since i'm still not entirely sure how redux works (or if it can even be used in this file, since i know i saw in the contributing guidelines that redux is only supposed to be used in certain files)

### CODE REVIEW

**Comment by deanveloper** [comment]
in my [previous MR](https://github.com/neatchee/mastodon/commit/856997e85f9d8287fc0957004d547457f473d423#diff-755d1a781c11cde3e55b7d1daa57c795dd710d5f4507fdd6846887f42f4bc619L51) i had accidentally set this margin to be a bit too large while experimenting with some changes and forgetting to discard them.

Before (bugged)
image

After (fixed)
image


Fixing this as a part of this MR. Should I make an issue for this or is this good enough?

**Comment by neatchee** [comment]
> in my [previous MR](https://github.com/neatchee/mastodon/commit/856997e85f9d8287fc0957004d547457f473d423#diff-755d1a781c11cde3e55b7d1daa57c795dd710d5f4507fdd6846887f42f4bc619L51) i had accidentally set this margin to be a bit too large while experimenting with some changes and forgetting to discard them.
> 
> Before (bugged) image
> 
> After (fixed) image
> 
> Fixing this as a part of this MR. Should I make an issue for this or is this good enough?

Let's do this in a separate PR. Emoji zooming is another feature I'd like to try to push up to glitch :)

**Review by neatchee — CHANGES_REQUESTED** [review]
todo: move the margin fix into a separate PR

**Comment by neatchee** [comment]
If this is a glitch-only setting in the pop-over UI I think enabling redux is fine; redux already triggers for, e.g., disabling collapsed toots (but not enabling? kinda weird but whatevs)

Alternatively, we could address the redux issue by tagging certain settings as "requires refresh" and triggering the refresh automatically when the pop-over is closed

**Comment by deanveloper** [comment]
I believe that it already publishes the setting update over redux, but my only issue is that I'm not quite sure how to listen for the change outside of React since I've only ever used React's helpers with Redux... I'll try to figure out how it works so that it can be updated live.

**Review by neatchee — APPROVED** [review]

**Comment by deanveloper** [comment]
Closing this PR and opening a new one, I removed the remote to the repo on my user since it's a lot easier to manage when there's only one remote LOL

**Pull request closed without merging**
